---
name: Tag release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Tag release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: tek
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: rm -rf /opt/hostedtoolcache
      - name: build static
        run: nix build .#hix.appimage
      - uses: softprops/action-gh-release@v2
        name: Create release
        with:
          prerelease: false
          make_latest: true
          files: |
            result/bin/hix
      - uses: DeterminateSystems/flakehub-push@main
        name: 'Publish to flakehub'
        with:
          visibility: public
