name: Tests basic 2
on:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  tests:
    env:
      hix_test_ci: 1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = https://tek.cachix.org
          extra-trusted-public-keys = tek.cachix.org-1:+sdc73WFq8aEKnrVv5j/kuhmnW2hQJuqdPJF5SnaCBk=
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: tek
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: rm -rf /opt/hostedtoolcache
    - run: git config --global user.name hix
    - run: git config --global user.email hix@tryp.io
    - run: nix run .#test-basic-2
    - run: nix flake check
