name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  hix_test_ci: 1
  LANG: en_US.UTF-8

jobs:

  checks:
    name: Prepare tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      tests: ${{ steps.ci-matrix.outputs.tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: download-buffer-size = 1000000000
      - name: Enable cachix
        uses: cachix/cachix-action@v16
        with:
          name: tek
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Free up space
        run: rm -rf /opt/hostedtoolcache
      - name: Flake checks
        run: nix --show-trace flake check
      - id: ci-matrix
        name: Output CI matrix
        run: |
          echo -n "tests=" >> "$GITHUB_OUTPUT"
          nix --show-trace eval --json .#ci-matrix >> "$GITHUB_OUTPUT"

  tests:
    name: 🛠️ ${{ matrix.test }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: checks
    strategy:
      matrix:
        test: ${{ fromJSON(needs.checks.outputs.tests) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: download-buffer-size = 1000000000
      - name: Enable cachix
        uses: cachix/cachix-action@v16
        with:
          name: tek
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Free up space
        run: rm -rf /opt/hostedtoolcache
      - name: Configure apparmor to permit appimages to execute
        run: sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0
      - name: Run test '${{ matrix.test }}'
        run: nix --show-trace run .#test -- ${{ matrix.test }}

  appimage:
    name: Build the AppImage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: download-buffer-size = 1000000000
      - name: Enable cachix
        uses: cachix/cachix-action@v16
        with:
          name: tek
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Free up space
        run: rm -rf /opt/hostedtoolcache
      - name: Build the AppImage
        run: nix --show-trace -L build .#min.appimage

  docs:
    name: Build the docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: download-buffer-size = 1000000000
      - name: Enable cachix
        uses: cachix/cachix-action@v16
        with:
          name: tek
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Free up space
        run: rm -rf /opt/hostedtoolcache
      - name: Build the docs
        run: nix --show-trace -L build .#docs
