name: Tests for managed bounds
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    env:
      hix_test_ci: 1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        extra-conf: |
          download-buffer-size = 1000000000
    - uses: cachix/cachix-action@v15
      with:
        name: tek
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: rm -rf /opt/hostedtoolcache
    - run: nix run .#test-managed
